### ISSUE TITLE
Fix KeyError

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/sardina#18]
When using the options `--no-commits --sloc --graphs` the graph generation fails because it doesn't have data about commits.  
Traceback:
```python
Generating graphs...
Traceback (most recent call last):
  File "./main.py", line 624, in <module>
    main()
  File "./main.py", line 618, in main
    print_all_stats(commits_stats, lines_stats, contributors_stats, use_cloc, generate_graphs)
  File "./main.py", line 475, in print_all_stats
    generate_figure([repo_commits[graph], yearly_repo_commits[graph], sloc_by_repo[graph]], os.path.join(graph_dir, f'{graph}.svg'))
KeyError: 'ansible-pxe'
```
'ansible-pxe' is the key that fails because it is the first repo when sorting alphabetically.

**Comment by e-caste** [comment]
Closed in #21
